name: bee
description: "More power Less code"
version: 1.0.0
repository: https://github.com/sakiatu/bee

environment:
  sdk: '>=3.3.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.2

